### ISSUE TITLE
Show default (UTC) time as well as IST in tmux statusbar

### ISSUE THREAD

**Issue by santosh** [santosh/.dotfiles#1]

**Comment by himanshu007-creator** [comment]
i would like to work . Please guide me further

**Comment by santosh** [comment]
@himanshu007-creator If you happen to use `tmux`, I maintain a config file at https://github.com/santosh/.dotfiles/blob/master/.tmux.conf. 

Right now, at the low right, the time shown is in local time (configured while installing OS). This used to work fine in my local install. 

![image](https://user-images.githubusercontent.com/1515991/114076105-e8665f80-98c3-11eb-8c59-b1ea379357d3.png)

But nowadays most of the time in tmux is in the cloud. I could configure my cloud instance to use IST, but that's not best practice and would lead to confusion. 

For this task you could research on `tmux status bar customization`. And for the getting the text to the statusbar, I hope you could use some Bash or Python script. 

Hint: If you are using `date` command to fetch time in IST, you can do `TZ=Asia/Kolkata date`.

Let me know how it goes.

**Comment by himanshu007-creator** [comment]
i will try my best to work on it :-)

**Comment by himanshu007-creator** [comment]
<code>set -g status-right '#(TZ="Asia/Kolkata" date +%%H:%%M:%%S)'</code>
this piece of code will do the trick. I need to paste it <a href="https://github.com/santosh/.dotfiles/blob/master/.tmux.conf">Here </a> right?

**Comment by santosh** [comment]
Yes, you are correct about the file. 

Also, make sure that I want both times. Separate them by `|`. Post a screenshot in the PR so I can see. 

Edit: Please note that if I use this config in my local installation (configured at installation as IST), it should show the same time in both. The key point to note is the first time shown will be systems local. The second one will be dynamic. I hope you understand. Let me know if there is any concern.

**Comment by himanshu007-creator** [comment]
> Yes, you are correct about the file.
> 
> Also, make sure that I want both times. Separate them by `|`. Post a screenshot in the PR so I can see.
> 
> Edit: Please note that if I use this config in my local installation (configured at installation as IST), it should show the same time in both. The key point to note is the first time shown will be systems local. The second one will be dynamic. I hope you understand. Let me know if there is any concern.

I am clear about your requirement but I am unable to figure it our. What exactly do I need to do now.
What I think is that, I can display one time as costom Time and second time in custom text field.
I would like if you can help me out here.

**Comment by santosh** [comment]
Well, this is weird. 

These commands work fine in bash.

```
ec2-user at ip-172-31-45-160 in ~ $ date +%H:%M:%S                                                 
11:58:47
ec2-user at ip-172-31-45-160 in ~ $ TZ=Asia/Kolkata date +%H:%M:%S                                 
17:29:05
```

But this config: 

    set -g status-right '#(date +%%H:%%M:%%S) | #(TZ="Asia/Kolkata" date +%%H:%%M:%%S)'

Renders the same time: 

![image](https://user-images.githubusercontent.com/1515991/114177402-ff579100-9959-11eb-93f9-275b264c498f.png)

Is your output any different @himanshu007-creator?

**Comment by santosh** [comment]
I had to force reload the config. I was trying to exit tmux and start again to load the config which didn't work. 

@himanshu007-creator  You can go ahead and raise the PR.

**Comment by himanshu007-creator** [comment]
> `set -g status-right '#(TZ="Asia/Kolkata" date +%%H:%%M:%%S)'`
> this piece of code will do the trick. I need to paste it [Here ](https://github.com/santosh/.dotfiles/blob/master/.tmux.conf) right?

With this additional line only right?

**Comment by santosh** [comment]
While I was researching on the issue, I found this simple theme.

```conf
set -g status-bg black
set -g status-fg white
set -g window-status-current-bg white
set -g window-status-current-fg black
set -g window-status-current-attr bold
```

For the content of the status bar, here are the left and right status bar. 

```conf
set -g status-left-length 30
set -g status-left '#[fg=green](#S) #(whoami)'
set -g status-right-length 40
set -g status-right "#[fg=white]#S #I:#P #[fg=yellow]:: [%d %b |#[fg=cyan] #(TZ=UTC date -u +%%H:%%M) UTC | #(TZ=Asia/Kolkata date +%%H:%%M) IST]"
```

For now, you can put the above configs and go ahead.
